services:
  # Frontend Service (serves static files via nginx)
  frontend:
    build: ./frontend
    restart: always
    networks:
      - devops-network

  # Backend Service (Port 3000 internally)
  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    # environment:
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - devops-network

  # Database Service (MySQL 8.0)
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #   - MYSQL_USER=${MYSQL_USER}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - devops-network

  # Nginx Reverse Proxy (The Gateway)
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "1234:80"
    depends_on:
      - frontend
      - backend
    networks:
      - devops-network

# Custom Docker Network
networks:
  devops-network:
    driver: bridge

# Data Persistence
volumes:
  db_data:
